CREATE TABLE ANIMALS.animal
(
    ID BIGINT NOT NULL PRIMARY KEY,
    NAME CHARACTER VARYING(255) NOT NULL,
    TYPE CHARACTER VARYING(255) NOT NULL

);


CREATE TABLE ANIMALS.zoo
(
    ID BIGINT NOT NULL PRIMARY KEY ,
    amountAnimals INTEGER NOT NULL,
    name character varying(255) not null,
    ANIMAL_ID BIGINT NOT NULL REFERENCES ANIMALS.ANIMAL(ID)

);

CREATE SEQUENCE animals.animal_seq INCREMENT 1 START 1000;
CREATE SEQUENCE animals.zoo_seq INCREMENT 1 START 1000;
